version: '3.7'
services:
  traefik:
    image: traefik:v2.4
    ports:
      - "80:80"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        # Enable traefik for this service
        - "traefik.enable=true"
        - "traefik.http.routers.traefik.rule=Host(`traefik.pd.com`)"
        - "traefik.http.services.traefik-service.loadbalancer.server.port=8080"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.swarmMode=true"
      - "--providers.docker.exposedByDefault=false"
      - "--providers.docker.network=traefik_proxy"
      # - "--accesslog"
      # - "--log.level=INFO"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik_proxy

networks:
  traefik_proxy:
    #  If we want traefik to be able to proxy to multiple stacks we need to have one external network!!
    external: true